version: '3.0'

services:
  db:
    container_name: db
    build: ./db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: uzk-admin
      POSTGRES_PASSWORD: LjVNCcNG5F5T
      POSTGRES_DB: uzk-info
    volumes: 
      - ./db/data/:/var/lib/postgresql/data